/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'publishedAt' : Time,
  'author' : string,
  'excerpt' : string,
  'category' : string,
}
export type Time = bigint;
export interface TripInquiry {
  'destination' : string,
  'name' : string,
  'travelDate' : Time,
  'phone' : string,
  'specialRequirements' : string,
  'budgetRange' : string,
  'numberOfGuests' : bigint,
}
export interface _SERVICE {
  'createBlogPost' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'getAllBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getAllInquiries' : ActorMethod<[], Array<TripInquiry>>,
  'getBlogPostById' : ActorMethod<[bigint], BlogPost>,
  'init' : ActorMethod<[], undefined>,
  'submitInquiry' : ActorMethod<[TripInquiry], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];