/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const BlogPost = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'publishedAt' : Time,
  'author' : IDL.Text,
  'excerpt' : IDL.Text,
  'category' : IDL.Text,
});
export const TripInquiry = IDL.Record({
  'destination' : IDL.Text,
  'name' : IDL.Text,
  'travelDate' : Time,
  'phone' : IDL.Text,
  'specialRequirements' : IDL.Text,
  'budgetRange' : IDL.Text,
  'numberOfGuests' : IDL.Nat,
});

export const idlService = IDL.Service({
  'createBlogPost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getAllInquiries' : IDL.Func([], [IDL.Vec(TripInquiry)], ['query']),
  'getBlogPostById' : IDL.Func([IDL.Nat], [BlogPost], ['query']),
  'init' : IDL.Func([], [], []),
  'submitInquiry' : IDL.Func([TripInquiry], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const BlogPost = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'publishedAt' : Time,
    'author' : IDL.Text,
    'excerpt' : IDL.Text,
    'category' : IDL.Text,
  });
  const TripInquiry = IDL.Record({
    'destination' : IDL.Text,
    'name' : IDL.Text,
    'travelDate' : Time,
    'phone' : IDL.Text,
    'specialRequirements' : IDL.Text,
    'budgetRange' : IDL.Text,
    'numberOfGuests' : IDL.Nat,
  });
  
  return IDL.Service({
    'createBlogPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getAllInquiries' : IDL.Func([], [IDL.Vec(TripInquiry)], ['query']),
    'getBlogPostById' : IDL.Func([IDL.Nat], [BlogPost], ['query']),
    'init' : IDL.Func([], [], []),
    'submitInquiry' : IDL.Func([TripInquiry], [], []),
  });
};

export const init = ({ IDL }) => { return []; };